openapi: 3.0.0
info:
  title: OrientAPI
  description: OpenAPI definition to documentation for the Orient RESTful API.
  version: 0.1.0
servers:
  - url: https://orienti.app/api/v1
    description: Production
  - url: https://orienti.jakubdubec.me/api/v1
    description: Staging test server
  - url: http://127.0.0.1:8000/api/v1
    description: Local development server
paths:
  /sync/:
    $ref: "views/sync.yaml#/Sync"
